server:
  port: 0 # Use a random available port

spring:
  application:
    name: WALLET-SERVICE # The name for Eureka registration
  datasource:
    url: jdbc:mysql://localhost:3306/paypal_wallets # Connects to the new wallets DB
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates the 'wallets' table
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/